print(type(1234567))
print(type(24.05))
print(type(6+4j))
print(type("hello letsupgrade"))
print(type(["AI","ML","DL"]))
print(type((1,2,3,4,5,6)))
print(type({1:"ABC", 2:"DEF", 3:"GHI"}))
print(type(True))
print(type(frozenset({"AI", "ML", "DL"})))
print(type(b"Praveen"))
print(type(bytearray(10)))
print(type(range(20)))
print(type(memoryview(bytes(2))))
